name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_release_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run test
      - run: npm run build
      - name: get-npm-version
        if: github.event_name == 'push'
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: create release
        if: github.event_name == 'push'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/*"
          name: Release ${{ steps.package-version.outputs.version }}.${{ github.run_number }}
          tag: v${{ steps.package-version.outputs.version }}.${{ github.run_number }}
      - name: deploy
        if: github.event_name == 'push'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install awscli
          aws s3 sync --acl public-read --delete ./build s3://www.quinnweber.com
          aws configure set preview.cloudfront true
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
