name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # registry-url: https://registry.npmjs.org/
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: deploy
        # if: github.event_name == 'push'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install awscli
          aws s3 sync --acl public-read --delete ./out s3://www.quinnweber.com
          aws configure set preview.cloudfront true
          aws cloudfront create-invalidation --distribution-id E1H4R1IMHN7A8Z --paths '/*'
