name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run test
      - run: npm run build
  infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install
      - uses: pulumi/actions@v3
        with:
          work-dir: infrastructure
          command: up
          expect-no-changes: true
          stack-name: personal-site
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
  release_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install --omit=dev
      - run: npm run build
      - name: get-npm-version
        id: package-version
        run: |
          MAJOR_MINOR=$(node -e "console.log(JSON.parse(fs.readFileSync('package.json')).version.replace(/\.\d+$/, ''))")
          echo "package-version=$(echo $MAJOR_MINOR)" >> $GITHUB_OUTPUT
      - run: zip -r build.zip build/*
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build.zip"
          name: Release ${{ steps.package-version.outputs.package-version }}.${{ github.run_number }}
          tag: v${{ steps.package-version.outputs.package-version }}.${{ github.run_number }}
      - name: deploy
        if: github.event_name == 'push'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install awscli
          aws s3 sync --acl public-read --delete ./build ${{ secrets.S3_BUCKET }}
          aws configure set preview.cloudfront true
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
